# Generated by Django 3.0.8 on 2021-06-16 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_users',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_type', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='course_list',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(default='course-no-name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='student_user',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_user',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='student_course_bridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.course_list')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student_user')),
            ],
        ),
        migrations.AddField(
            model_name='course_list',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher_user'),
        ),
    ]
