# Generated by Django 3.2.4 on 2021-06-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course_list",
            name="course_desc",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="course_list",
            name="course_id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="course_list",
            name="course_name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
