# Generated by Django 3.2.4 on 2021-07-04 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 13, 26, 8, 884719)),
        ),
    ]
