# Generated by Django 3.0.8 on 2021-06-18 18:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210617_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_assignments',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.course_list')),
            ],
        ),
    ]
