# Generated by Django 3.2.4 on 2021-06-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20210626_1442"),
    ]

    operations = [
        migrations.AddField(
            model_name="course_list",
            name="enrollment_code",
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
