# Generated by Django 3.2.4 on 2021-06-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_course_list_enrollment_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course_list",
            name="enrollment_code",
            field=models.CharField(default="000000", max_length=6),
        ),
    ]
