# Generated by Django 3.2.4 on 2021-07-04 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210704_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 13, 27, 5, 599994)),
        ),
    ]
