# Generated by Django 3.0.8 on 2021-06-19 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_assignments',
            name='assignment_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_assignments',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 17, 47, 0, 635120)),
        ),
        migrations.AlterField(
            model_name='student_assignments',
            name='assignment_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
