# Generated by Django 3.2.4 on 2021-06-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_course_list_enrollment_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_assignments",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="student_assignments",
            name="assignment_body",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="student_assignments",
            name="assignment_name",
            field=models.TextField(null=True),
        ),
    ]
