<<<<<<< HEAD
# Generated by Django 3.2.4 on 2021-07-04 15:10
=======
# Generated by Django 3.2.4 on 2021-07-04 14:26
>>>>>>> c8548d5d397b3c00799ffe569b63a5029e480ce0

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_submission_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_date',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 20, 40, 39, 277564)),
=======
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 14, 26, 20, 131812)),
>>>>>>> c8548d5d397b3c00799ffe569b63a5029e480ce0
        ),
    ]
