# Generated by Django 3.2.4 on 2021-06-28 14:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20210627_0708"),
    ]

    operations = [
        migrations.CreateModel(
            name="submission",
            fields=[
                ("submission_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "submission_date",
                    models.DateTimeField(
                        default=datetime.datetime(2021, 6, 28, 14, 11, 4, 578204)
                    ),
                ),
                ("submission_status", models.IntegerField()),
                ("submission_code", models.TextField(blank=True, null=True)),
                (
                    "submission_lang",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "assignment_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.student_assignments",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.student_user",
                    ),
                ),
            ],
        ),
    ]
