# Generated by Django 3.2.4 on 2021-07-01 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 7, 22, 44, 833308)),
        ),
    ]
