# Generated by Django 3.0.8 on 2021-06-23 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210624_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_assignments',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 0, 38, 36, 877106)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 0, 38, 36, 878104)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_lang',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
